### ISSUE TITLE
[SECURITY] pin decryption

### ISSUE THREAD

**Issue by nagayev** [TwoEightNine/XVII#2]
Hello.
I could hack pin decryption and write gist.
[link](https://gist.github.com/nagayev/5e05d9756b011c55802cfda0acbee256)

**Comment by TwoEightNine** [comment]
yes, you can decrypt hashed with salt pin. but firstly you got to access this pin. if you have an access to your shared preferences, you can hack your own pin?? if you hav an access to other user device's shared preferences, is this pin exactly what you want to explore, really?
