### ISSUE TITLE
Видео из личных сообщений не проигрываются

### ISSUE THREAD

**Issue by NChechulin** [TwoEightNine/XVII#5]
При попытке посмотреть видео вк выдает ошибку.
Демо можно посмотреть тут: https://vimeo.com/428029830

**Comment by TwoEightNine** [comment]
Начиная с версии 6.0 плеер открывается не в WebView, а в custom tab (при наличии), где подхватывается авторизация. Такое решение позволяет воспроизводить видео из личных сообщений.
