### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by silentbay** [TwoEightNine/XVII#6]
День добрый.
Можно ли опубликовать приложение в репозиторий f-droid.org?
Основные условия для этого выполняются.

**Comment by TwoEightNine** [comment]
Добрый день. Совсем недавно мое приложение не удовлетворяло требованиям. Впрочем, ознакомлюсь с требованиями снова, и, если они будут легко выполнимы, с удовольствием размещу. О сроках не скажу

**Comment by butyoutried** [comment]
Присоединяюсь! Ждем в F-Droid или хотя бы пока в [IzzyOnDroid Repository](https://apt.izzysoft.de/fdroid/index/info).

**Comment by butyoutried** [comment]
https://f-droid.org/packages/com.twoeightnine.root.xvii/

Мои поздравления.

**Comment by TwoEightNine** [comment]
Ссылки в README и группе обновлю в ближайшее время. 

Для истории:
 - https://gitlab.com/fdroid/rfp/-/issues/1861
 - https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9921
