### ISSUE TITLE
Выборочное отключение уведомлений для чатов/диалогов

### ISSUE THREAD

**Issue by Abyss777** [TwoEightNine/XVII#9]
В оригинальном приложении есть возможность отключать уведомления в некоторых чатах, причем упоминания в этом чате уведомляются.
Хорошо бы добавить такой функционал в ваше приложение.
Как я понимаю это не функция сайта, а самого приложения, придется где-то локально хранить эти настройки.

**Comment by TwoEightNine** [comment]
если перейти в детали чата (профиль человека или детали беседы), можно увидеть свич уведомлений, который делает то, что вы говорите. это вам подходит?

**Comment by Abyss777** [comment]
Точно, спасибо! А можно переключатель и кнопку выйти сделать до закрепленного сообщения? Если закреп длинный то этот свитч далеко и не очевидно его присутствие.

**Comment by TwoEightNine** [comment]
@Abyss777, добавил транкейт закрепа в 6.1.7, теперь такой проблемы возникнуть не должно
